name: CI Pipeline for DevOps Project

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (without version change)
        run: mvn clean install --no-transfer-progress

      - name: List files in target directory
        run: ls -la target/

      - name: Build Docker Image
        run: docker build --no-cache -t devops-app .

      - name: Commit and Push Updated pom.xml (if any changes)
        run: |
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          
          git add pom.xml
          git commit -m "chore: update pom.xml" || { echo "No changes to commit"; exit 1; }

         
          git config pull.rebase false

          
          git pull origin develop --allow-unrelated-histories --no-edit || { echo "Git pull failed: Merge conflict detected"; exit 1; }

          
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:develop || { echo "Git push failed"; exit 1; }

      - name: Run tests
        run: mvn test
