name: CI Pipeline for DevOps Project

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Increment Version in pom.xml
        run: |
          # Increment the version using a simple command. Adjust this to your needs.
          mvn versions:set -DnewVersion=1.0.$(date +%s) -DgenerateBackupPoms=false
          mvn versions:commit      

      - name: Build Docker Image
        run: |
          docker build -t devops-app .      

      - name: Run tests
        run: mvn test
