name: CI Pipeline for DevOps Project

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: List files in target directory
        run: ls -la target/

      - name: Build Docker Image
        run: docker build --no-cache -t devops-app .